# Name of our workflow
name: 'Build and Deploy GitHub Pages'

# Event triggering the workflow
on:
  push:
    branches:
      - main # Event only triggered when pushing on the master branch
jobs:
  # Our job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. We gather repository's content
      - name: 'Checkout'
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip3 install r requirements.txt
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
